services:
  mongo:
    image: mongo:6.0
    container_name: quotes-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/dockerfile.backend
    container_name: quotes-backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/quotesapi
      FRONTEND_URL: http://localhost:3000

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/dockerfile.frontend
    container_name: quotes-frontend
    restart: always
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: "Quotes API"

volumes:
  mongo_data:
