# Build Stage
FROM node:18-alpine AS builder

WORKDIR /app
# Copy package files and install dependencies from frontend context (../Frontend)
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build

# Production Stage
FROM nginx:1.25-alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
