# Build Stage
FROM node:20-alpine AS builder

WORKDIR /app
# Copy package files from backend context (../Backend)
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .

# Production Stage
FROM node:18-alpine AS production

WORKDIR /app
COPY --from=builder /app ./
ENV NODE_ENV=production
EXPOSE 5000

CMD ["node", "server.js"]
